version: 2

models:  

  - name: W_ACCOUNTS_D
    description: This is the acounts dimension table
    columns:
      - name: K_ACCOUNT_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the account
  - name: W_ASSETS_D
    description: This is the assets dimension table
    columns:
      - name: K_ASSET_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the asset
  - name: W_CONTACTS_D
    description: This is the contacts dimension table
    columns:
      - name: K_CONTACT_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the contact        
  - name: W_DATE_D
    description: This is the date dimension table
    columns:
      - name: K_DATE_BK        
        tests:
          - unique
          - not_null
        description: Date Key
  - name: W_EMPLOYEES_D
    description: This is the employees dimension table
    columns:
      - name: K_EMPLOYEE_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the employee
  - name: W_INVOICES_F
    description: This is the invoices fact table
    columns:
      - name: K_INVOICE_LINE_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the invoices fact

      - name: K_ACCOUNT_DLHK        
        tests:
          - relationships:
              to: ref('W_ACCOUNTS_D')
              field: K_ACCOUNT_DLHK                

      - name: K_ITEM_DLHK        
        tests:
          - relationships:
              to: ref('W_ITEMS_D')
              field: K_ITEM_DLHK        
      
      - name: K_CONTACT_DLHK        
        tests:
          - relationships:
              to: ref('W_CONTACTS_D')
              field: K_CONTACT_DLHK

  - name: W_ITEMS_D
    description: This is the items dimension table
    columns:
      - name: K_ITEM_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the item          
  
  - name: W_JOURNAL_F
    description: This is the journal fact table
    columns:
      - name: K_JOURNAL_LINE_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the journal

      - name: K_ACCOUNT_DLHK        
        tests:
          - relationships:
              to: ref('W_ACCOUNTS_D')
              field: K_ACCOUNT_DLHK                


  - name: W_PAYMENTS_F
    description: This is the payments fact table
    columns:
      - name: K_PAYMENT_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the payment


      - name: K_ACCOUNT_DLHK        
        tests:
          - relationships:
              to: ref('W_ACCOUNTS_D')
              field: K_ACCOUNT_DLHK                

   
  - name: W_PURCHASE_ORDERS_F
    description: This is the purchase orders fact table
    columns:
      - name: K_PURCHASE_LINE_ITEM_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the purchase order

        
      - name: K_ACCOUNT_DLHK        
        tests:
          - relationships:
              to: ref('W_ACCOUNTS_D')
              field: K_ACCOUNT_DLHK                

      - name: K_ITEM_DLHK        
        tests:
          - relationships:
              to: ref('W_ITEMS_D')
              field: K_ITEM_DLHK        
      
      - name: K_CONTACT_DLHK        
        tests:
          - relationships:
              to: ref('W_CONTACTS_D')
              field: K_CONTACT_DLHK

  - name: W_RECEIPTS_F
    description: This is the receipts fact table
    columns:
      - name: K_RECEIPT_LINE_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the receipt

    
      - name: K_ACCOUNT_DLHK        
        tests:
          - relationships:
              to: ref('W_ACCOUNTS_D')
              field: K_ACCOUNT_DLHK                

      - name: K_ITEM_DLHK        
        tests:
          - relationships:
              to: ref('W_ITEMS_D')
              field: K_ITEM_DLHK        
      
      - name: K_CONTACT_DLHK        
        tests:
          - relationships:
              to: ref('W_CONTACTS_D')
              field: K_CONTACT_DLHK

      - name: K_SALES_TERM_DLHK        
        tests:
          - relationships:
              to: ref('W_TERM_D')
              field: K_TERM_DLHK

      - name: K_VENDOR_DLHK        
        tests:
          - relationships:
              to: ref('W_VENDORS_D')
              field: K_VENDOR_DLHK

      - name: K_BILL_CURRENCY_DLHK        
        tests:
          - relationships:
              to: ref('W_CURRENCY_D')
              field: K_CURRENCY_DLHK

      - name: K_ITEM_EXPENSE_DLHK        
        tests:
          - relationships:
              to: ref('W_ITEMS_D')
              field: K_ITEM_DLHK

  - name: W_PURCHASES_F
    description: This is the purchases fact table
    columns:
      - name: K_PURCHASE_LINE_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the purchase line
    
      - name: K_ACCOUNT_DLHK        
        tests:
          - relationships:
              to: ref('W_ACCOUNTS_D')
              field: K_ACCOUNT_DLHK                

      - name: K_CUSTOMER_DLHK        
        tests:
          - relationships:
              to: ref('W_CUSTOMERS_D')
              field: K_CUSTOMER_DLHK        

      - name: K_VENDOR_DLHK        
        tests:
          - relationships:
              to: ref('W_VENDORS_D')
              field: K_VENDOR_DLHK

      - name: K_PURCHASE_CURRENCY_DLHK         
        tests:
          - relationships:
              to: ref('W_CURRENCY_D')
              field: K_CURRENCY_DLHK

      - name: K_ITEM_EXPENSE_DLHK        
        tests:
          - relationships:
              to: ref('W_ITEMS_D')
              field: K_ITEM_DLHK